#include <cstdio>

char s[105];

int main() {
  scanf("%s", s);
  int cnt = 0;
  if (s[0] == 'O') ++cnt;
  if (s[1] == 'O') ++cnt;
  if (s[2] == 'O') ++cnt;
  if (s[3] == 'O') ++cnt;
  if (s[4] == 'O') ++cnt;
  if (s[5] == 'O') ++cnt;
  if (s[6] == 'O') ++cnt;
  if (s[7] == 'O') ++cnt;
  if (s[8] == 'O') ++cnt;
  if (s[9] == 'O') ++cnt;
  if (s[10] == 'O') ++cnt;
  if (s[11] == 'O') ++cnt;
  if (s[12] == 'O') ++cnt;
  if (s[13] == 'O') ++cnt;
  if (s[14] == 'O') ++cnt;
  if (s[15] == 'O') ++cnt;
  if (s[16] == 'O') ++cnt;
  if (s[17] == 'O') ++cnt;
  if (s[18] == 'O') ++cnt;
  if (s[19] == 'O') ++cnt;
  if (s[20] == 'O') ++cnt;
  if (s[21] == 'O') ++cnt;
  if (s[22] == 'O') ++cnt;
  if (s[23] == 'O') ++cnt;
  if (s[24] == 'O') ++cnt;
  if (s[25] == 'O') ++cnt;
  if (s[26] == 'O') ++cnt;
  if (s[27] == 'O') ++cnt;
  if (s[28] == 'O') ++cnt;
  if (s[29] == 'O') ++cnt;
  if (s[30] == 'O') ++cnt;
  if (s[31] == 'O') ++cnt;
  if (s[32] == 'O') ++cnt;
  if (s[33] == 'O') ++cnt;
  if (s[34] == 'O') ++cnt;
  if (s[35] == 'O') ++cnt;
  if (s[36] == 'O') ++cnt;
  if (s[37] == 'O') ++cnt;
  if (s[38] == 'O') ++cnt;
  if (s[39] == 'O') ++cnt;
  if (s[40] == 'O') ++cnt;
  if (s[41] == 'O') ++cnt;
  if (s[42] == 'O') ++cnt;
  if (s[43] == 'O') ++cnt;
  if (s[44] == 'O') ++cnt;
  if (s[45] == 'O') ++cnt;
  if (s[46] == 'O') ++cnt;
  if (s[47] == 'O') ++cnt;
  if (s[48] == 'O') ++cnt;
  if (s[49] == 'O') ++cnt;
  if (s[50] == 'O') ++cnt;
  if (s[51] == 'O') ++cnt;
  if (s[52] == 'O') ++cnt;
  if (s[53] == 'O') ++cnt;
  if (s[54] == 'O') ++cnt;
  if (s[55] == 'O') ++cnt;
  if (s[56] == 'O') ++cnt;
  if (s[57] == 'O') ++cnt;
  if (s[58] == 'O') ++cnt;
  if (s[59] == 'O') ++cnt;
  if (s[60] == 'O') ++cnt;
  if (s[61] == 'O') ++cnt;
  if (s[62] == 'O') ++cnt;
  if (s[63] == 'O') ++cnt;
  if (s[64] == 'O') ++cnt;
  if (s[65] == 'O') ++cnt;
  if (s[66] == 'O') ++cnt;
  if (s[67] == 'O') ++cnt;
  if (s[68] == 'O') ++cnt;
  if (s[69] == 'O') ++cnt;
  if (s[70] == 'O') ++cnt;
  if (s[71] == 'O') ++cnt;
  if (s[72] == 'O') ++cnt;
  if (s[73] == 'O') ++cnt;
  if (s[74] == 'O') ++cnt;
  if (s[75] == 'O') ++cnt;
  if (s[76] == 'O') ++cnt;
  if (s[77] == 'O') ++cnt;
  if (s[78] == 'O') ++cnt;
  if (s[79] == 'O') ++cnt;
  if (s[80] == 'O') ++cnt;
  if (s[81] == 'O') ++cnt;
  if (s[82] == 'O') ++cnt;
  if (s[83] == 'O') ++cnt;
  if (s[84] == 'O') ++cnt;
  if (s[85] == 'O') ++cnt;
  if (s[86] == 'O') ++cnt;
  if (s[87] == 'O') ++cnt;
  if (s[88] == 'O') ++cnt;
  if (s[89] == 'O') ++cnt;
  if (s[90] == 'O') ++cnt;
  if (s[91] == 'O') ++cnt;
  if (s[92] == 'O') ++cnt;
  if (s[93] == 'O') ++cnt;
  if (s[94] == 'O') ++cnt;
  if (s[95] == 'O') ++cnt;
  if (s[96] == 'O') ++cnt;
  if (s[97] == 'O') ++cnt;
  if (s[98] == 'O') ++cnt;
  if (s[99] == 'O') ++cnt;

  if (cnt == 1) printf("Ya\n");
  else printf("Tidak\n");

  return 0;
}
